apiVersion: v1
kind: Service
metadata:
  name: load-balancer
  labels:
    app: react-docker
spec:
  type: LoadBalancer
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
    nodePort: 31000
  selector:
    app: react-docker
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: react-docker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react-docker
  template:
    metadata:
      labels:
        app: react-docker
    spec:
      containers:
      - name: react-docker
        image: docker.io/shuaishen/frontdonto:08
        ports:
        - containerPort: 3000
        env:
          - name: REACT_APP_API
            value: "http://192.168.0.16:32000"